# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatCpTb',
            fields=[
                ('cp_cd', models.CharField(db_column='CP_CD', max_length=10, primary_key=True, serialize=False)),
                ('cp_nm', models.CharField(db_column='CP_NM', max_length=255)),
                ('cp_kor_nm', models.CharField(db_column='CP_KOR_NM', max_length=255)),
                ('cp_desc', models.TextField(db_column='CP_DESC')),
            ],
            options={
                'db_table': 'DAT_CP_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatMedTb',
            fields=[
                ('med_cd', models.CharField(db_column='MED_CD', max_length=10, primary_key=True, serialize=False)),
                ('med_nm', models.CharField(db_column='MED_NM', max_length=255)),
                ('med_company_nm', models.CharField(db_column='MED_COMPANY_NM', max_length=255)),
                ('med_capa', models.CharField(db_column='MED_CAPA', max_length=255)),
                ('med_standard', models.CharField(db_column='MED_STANDARD', max_length=255)),
                ('med_unit', models.CharField(db_column='MED_UNIT', max_length=255)),
                ('med_pro', models.CharField(db_column='MED_PRO', max_length=255)),
                ('med_cate', models.CharField(db_column='MED_CATE', max_length=255)),
                ('med_inject', models.CharField(db_column='MED_INJECT', max_length=255)),
            ],
            options={
                'db_table': 'DAT_MED_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DurAgeTabooTb',
            fields=[
                ('dat_num', models.AutoField(db_column='DAT_NUM', primary_key=True, serialize=False)),
                ('cp_cd', models.CharField(db_column='CP_CD', max_length=255)),
                ('dat_age', models.CharField(db_column='DAT_AGE', max_length=255)),
                ('dat_age_type', models.CharField(db_column='DAT_AGE_TYPE', max_length=255)),
                ('dat_shape', models.CharField(db_column='DAT_SHAPE', max_length=255)),
                ('dat_note', models.CharField(db_column='DAT_NOTE', max_length=255)),
            ],
            options={
                'db_table': 'DUR_AGE_TABOO_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DurCapaCautTb',
            fields=[
                ('cp_nm', models.CharField(db_column='CP_NM', max_length=255, primary_key=True, serialize=False)),
                ('dcc_shape', models.CharField(db_column='DCC_SHAPE', max_length=255)),
                ('dcc_max_capa', models.CharField(db_column='DCC_MAX_CAPA', max_length=255)),
                ('dcc_note', models.CharField(db_column='DCC_NOTE', max_length=255)),
            ],
            options={
                'db_table': 'DUR_CAPA_CAUT_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DurCombiTabooTb',
            fields=[
                ('cp_nm_1', models.CharField(db_column='CP_NM_1', max_length=255, primary_key=True, serialize=False)),
                ('cp_nm_2', models.CharField(db_column='CP_NM_2', max_length=255)),
                ('dct_exception', models.CharField(db_column='DCT_EXCEPTION', max_length=255)),
                ('dct_note', models.CharField(db_column='DCT_NOTE', max_length=255)),
            ],
            options={
                'db_table': 'DUR_COMBI_TABOO_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DurEffectCautTb',
            fields=[
                ('cp_nm', models.CharField(db_column='CP_NM', max_length=255, primary_key=True, serialize=False)),
                ('dec_effect_group', models.CharField(db_column='DEC_EFFECT_GROUP', max_length=255)),
                ('dec_cate_nm', models.CharField(db_column='DEC_CATE_NM', max_length=255)),
                ('dec_note', models.CharField(db_column='DEC_NOTE', max_length=255)),
            ],
            options={
                'db_table': 'DUR_EFFECT_CAUT_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DurInjectCautTb',
            fields=[
                ('cp_nm', models.CharField(db_column='CP_NM', max_length=255, primary_key=True, serialize=False)),
                ('dic_shape', models.CharField(db_column='DIC_SHAPE', max_length=255)),
                ('dic_cp_content', models.CharField(db_column='DIC_CP_CONTENT', max_length=255)),
                ('dic_max_period', models.CharField(db_column='DIC_MAX_PERIOD', max_length=255)),
            ],
            options={
                'db_table': 'DUR_INJECT_CAUT_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DurOldCautTb',
            fields=[
                ('cp_nm', models.CharField(db_column='CP_NM', max_length=255, primary_key=True, serialize=False)),
                ('doc_shape', models.CharField(db_column='DOC_SHAPE', max_length=255)),
            ],
            options={
                'db_table': 'DUR_OLD_CAUT_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MbInfoTb',
            fields=[
                ('mb_id', models.CharField(db_column='MB_ID', max_length=25, primary_key=True, serialize=False)),
                ('mb_terms_agr', models.CharField(db_column='MB_TERMS_AGR', max_length=1)),
                ('mb_privacy_agr', models.CharField(db_column='MB_PRIVACY_AGR', max_length=1)),
                ('mb_reg_dtt', models.DateTimeField(db_column='MB_REG_DTT')),
                ('mb_serv_type', models.CharField(db_column='MB_SERV_TYPE', max_length=25)),
            ],
            options={
                'db_table': 'MB_INFO_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MbProfileTb',
            fields=[
                ('pf_id', models.AutoField(db_column='PF_ID', primary_key=True, serialize=False)),
                ('pf_rel', models.CharField(db_column='PF_REL', max_length=255)),
                ('pf_sex', models.CharField(db_column='PF_SEX', max_length=1)),
                ('pf_birth_year', models.CharField(db_column='PF_BIRTH_YEAR', max_length=4)),
                ('pf_sido', models.CharField(db_column='PF_SIDO', max_length=255)),
                ('pf_sigungu', models.CharField(db_column='PF_SIGUNGU', max_length=255)),
                ('pf_create_dtt', models.DateTimeField(db_column='PF_CREATE_DTT')),
                ('pf_modify_dtt', models.DateTimeField(db_column='PF_MODIFY_DTT')),
            ],
            options={
                'db_table': 'MB_PROFILE_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysCdgTb',
            fields=[
                ('cdg_id', models.CharField(db_column='CDG_ID', max_length=25, primary_key=True, serialize=False)),
                ('cdg_nm', models.CharField(db_column='CDG_NM', max_length=255)),
            ],
            options={
                'db_table': 'SYS_CDG_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysCntTb',
            fields=[
                ('cnt_id', models.CharField(db_column='CNT_ID', max_length=25, primary_key=True, serialize=False)),
                ('cnt_val', models.IntegerField(db_column='CNT_VAL')),
            ],
            options={
                'db_table': 'SYS_CNT_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MbMsgTb',
            fields=[
                ('pf', models.ForeignKey(db_column='PF_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.MbProfileTb')),
                ('msg_num', models.IntegerField(db_column='MSG_NUM')),
                ('msg_type', models.CharField(db_column='MSG_TYPE', max_length=255)),
                ('msg_val', models.TextField(db_column='MSG_VAL')),
                ('msg_dt', models.DateField(db_column='MSG_DT')),
                ('msg_time', models.TimeField(db_column='MSG_TIME')),
            ],
            options={
                'db_table': 'MB_MSG_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MbPrTb',
            fields=[
                ('pf', models.ForeignKey(db_column='PF_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.MbProfileTb')),
                ('pr_id', models.CharField(db_column='PR_ID', max_length=10)),
                ('pr_hosp_nm', models.CharField(db_column='PR_HOSP_NM', max_length=255)),
                ('pr_grant_dt', models.DateField(db_column='PR_GRANT_DT')),
                ('pr_reg_type', models.CharField(db_column='PR_REG_TYPE', max_length=255)),
                ('pr_reg_dtt', models.DateTimeField(db_column='PR_REG_DTT')),
            ],
            options={
                'db_table': 'MB_PR_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysCddTb',
            fields=[
                ('cdg', models.ForeignKey(db_column='CDG_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.SysCdgTb')),
                ('cdd_id', models.CharField(db_column='CDD_ID', max_length=255)),
                ('cdd_val', models.CharField(db_column='CDD_VAL', max_length=255)),
            ],
            options={
                'db_table': 'SYS_CDD_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MbTmedTb',
            fields=[
                ('pf', models.ForeignKey(db_column='PF_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='profile_id', serialize=False, to='api.MbPrTb')),
                ('tmed_num', models.IntegerField(db_column='TMED_NUM')),
                ('tmed_qty', models.IntegerField(db_column='TMED_QTY')),
                ('tmed_times', models.IntegerField(db_column='TMED_TIMES')),
                ('tmed_day_cnt', models.IntegerField(db_column='TMED_DAY_CNT')),
                ('tmed_start_dt', models.DateField(db_column='TMED_START_DT')),
                ('tmed_end_dt', models.DateField(db_column='TMED_END_DT')),
                ('tmed_modify_dtt', models.DateTimeField(db_column='TMED_MODIFY_DTT')),
            ],
            options={
                'db_table': 'MB_TMED_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MbTmeddTb',
            fields=[
                ('pf', models.ForeignKey(db_column='PF_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='profile_id', serialize=False, to='api.MbTmedTb')),
                ('tmedd_num', models.IntegerField(db_column='TMEDD_NUM')),
                ('tmedd_dt', models.DateField(db_column='TMEDD_DT')),
                ('tmedd_slot', models.CharField(db_column='TMEDD_SLOT', max_length=255)),
                ('tmedd_cfm', models.CharField(db_column='TMEDD_CFM', max_length=1)),
            ],
            options={
                'db_table': 'MB_TMEDD_TB',
                'managed': False,
            },
        ),
    ]
