# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='MbTmedTbTemp',
            fields=[
                ('pf', models.ForeignKey(db_column='PF_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='profile_id', serialize=False, to='api.MbPrTb')),
                ('tmed_num', models.IntegerField(db_column='TMED_NUM')),
                ('tmed_qty', models.IntegerField(db_column='TMED_QTY')),
                ('tmed_times', models.IntegerField(db_column='TMED_TIMES')),
                ('tmed_day_cnt', models.IntegerField(db_column='TMED_DAY_CNT')),
                ('tmed_start_dt', models.DateField(db_column='TMED_START_DT')),
                ('tmed_end_dt', models.DateField(db_column='TMED_END_DT')),
                ('tmed_modify_dtt', models.DateTimeField(db_column='TMED_MODIFY_DTT')),
            ],
            options={
                'db_table': 'MB_TMED_TB',
                'managed': False,
            },
        ),
    ]
